name: CI/CD Pipeline
# create release for staging and production
# with ability to pus hto the correct ecr registry
# likely create my own ecr registry first not through terraform
on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]
env:
  AWS_REGION: us-east-1
  ENVIRONMENT: staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: '3.x'  # Specify the version of Task you're using
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run auto:dispatcher:apply:staging task
      run: task auto:dispatcher:apply:staging

    # todo: add paths to listen to in order to deploy changes to dispatcher and operator separately 
    # todo: add an action that runs unit tests 
    # todo: crate separate ci/cd flows for dispatcher vs operator, staging vs production, push to main vs pull request