services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=your_username
      - RABBITMQ_DEFAULT_PASS=your_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
  api:    
    build: .    
    scale: 25
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "50051"

volumes:
  rabbitmq_data:
    name: rabbitmq_data