services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    restart: unless-stopped
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_auth_backend_oauth2 &&
             rabbitmq-server"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
  # api:    
  #   build: .    
  #   scale: 25
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   ports:
  #     - "50051"

volumes:
  rabbitmq_data:
    name: rabbitmq_data