version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: postgres:latest
    volumes:
      - ./sql/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
        psql -h postgres -U postgres -d postgres -f /migrations/up.sql
      "
    environment:
      PG_PASSWORD: postgres

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    scale: 25
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    