version: '3'

tasks:
  generate-proto:
        desc: |
          Generate Protobuf client and server code
        cmds:
          -  protoc --go_out=. --go_opt=paths=source_relative  --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/service.proto
  migrate:up:local:
    cmds:
      - migrate -path sql/migrations/ -database "postgresql://postgres:postgres@localhost:5438/?sslmode=disable" -verbose up
  migrate:create:
    vars:
        NAME: "{{.NAME}}"
    cmds:
      - migrate create -ext sql -dir sql/migrations/ -seq {{.NAME}}
  

